Repository 1Panel-dev/appstore, pull requests merged in 2023-03, with the labels that each got.

#2 feat: add uptime-kuma to appstore list
  apps/list.json
  apps/uptime-kuma/metadata/logo.svg
  apps/uptime-kuma/versions/1.20.2/README.md
  apps/uptime-kuma/versions/1.20.2/config.json
  apps/uptime-kuma/versions/1.20.2/docker-compose.yml
Labels: release-note, lgtm

#1 feat: add wiki.js to appstore list
  apps/list.json
  apps/wikijs/metadata/logo.svg
  apps/wikijs/versions/2.5.298/README.md
  apps/wikijs/versions/2.5.298/config.json
  apps/wikijs/versions/2.5.298/docker-compose.yml
Labels: release-note

#7 feat: 删除 wordpress 6.0.1 版本
  apps/wordpress/versions/6.0.1/README.md
  apps/wordpress/versions/6.0.1/config.json
  apps/wordpress/versions/6.0.1/docker-compose.yml
  apps/wordpress/versions/6.0.2/docker-compose.yml
Labels: do-not-merge/release-note-label-needed

#8 feat: redis-commander 增加数据库选择
  apps.json
  apps/redis-commander/versions/0.8.1/config.json
  apps/redis-commander/versions/0.8.1/docker-compose.yml
Labels: do-not-merge/release-note-label-needed

#13 feat: 修改 wiki.js 默认数据库服务为 mysql
  apps/wikijs/versions/2.5.298/config.json
Labels: do-not-merge/release-note-label-needed

#10 chore: 应用软件描述文案优化
  apps/list.json
Labels: do-not-merge/release-note-label-needed

#11 chore: 应用商店增加 “运行环境” 分类
  apps/list.json
Labels: do-not-merge/release-note-label-needed
