Repository 1Panel-dev/appstore, pull requests merged in 2023-05, with the labels that each got.

#35 fix: 修复了安装 Gitea 时没有校验端口的问题
  apps/gitea/versions/1.19.1/config.json
Labels: do-not-merge/release-note-label-needed, lgtm

#15 feat: add alist
  apps/alist/metadata/app.json
  apps/alist/metadata/logo.png
  apps/alist/versions/3.15.0/README.md
  apps/alist/versions/3.15.0/config.json
  apps/alist/versions/3.15.0/docker-compose.yml
Labels: do-not-merge/release-note-label-needed

#9 将 VoceChat 应用商店列表
  apps/vocechat/metadata/logo.png
  apps/vocechat/versions/0.3.0/README.md
  apps/vocechat/versions/0.3.0/config.json
  apps/vocechat/versions/0.3.0/docker-compose.yml
Labels: do-not-merge/release-note-label-needed

#17 Adminer数据库管理工具
  apps/adminer/metadata/app.json
  apps/adminer/metadata/logo.png
  apps/adminer/versions/4.8.1/README.md
  apps/adminer/versions/4.8.1/config.json
  apps/adminer/versions/4.8.1/docker-compose.yml
Labels: do-not-merge/release-note-label-needed

#65 feat: 删除一些无用的文件
  apps/ALS/metadata/logo.png
  apps/ALS/versions/latest/README.md
  apps/ALS/versions/latest/config.json
  apps/ALS/versions/latest/docker-compose.yml
  apps/alist/versions/3.16.0/config.json
  apps/alist/versions/3.16.0/data/mnt/.gitkeep
  apps/alist/versions/3.16.3/README.md
  apps/alist/versions/3.16.3/config.json
  apps/alist/versions/3.16.3/data/data/.gitkeep
  apps/alist/versions/3.16.3/data/mnt/.gitkeep
  apps/alist/versions/3.16.3/docker-compose.yml
  apps/alist/versions/latest/README.md
  apps/alist/versions/latest/config.json
  apps/alist/versions/latest/data/data/.gitkeep
  apps/alist/versions/latest/data/mnt/.gitkeep
  apps/alist/versions/latest/docker-compose.yml
  apps/alistv2/metadata/app.json
  apps/alistv2/metadata/logo.png
  apps/alistv2/versions/3.15.0/README.md
  apps/alistv2/versions/3.15.0/config.json
  apps/alistv2/versions/3.15.0/docker-compose.yml
  apps/baidunetdisk/metadata/logo.png
  apps/baidunetdisk/versions/4.14.6/README.md
  apps/baidunetdisk/versions/4.14.6/config.json
  apps/baidunetdisk/versions/4.14.6/data/config/.gitkeep
  apps/baidunetdisk/versions/4.14.6/data/downloads/.gitkeep
  apps/baidunetdisk/versions/4.14.6/docker-compose.yml
  apps/baidunetdisk/versions/4.17.7/README.md
  apps/baidunetdisk/versions/4.17.7/config.json
  apps/baidunetdisk/versions/4.17.7/data/config/.gitkeep
  apps/baidunetdisk/versions/4.17.7/data/downloads/.gitkeep
  apps/baidunetdisk/versions/4.17.7/docker-compose.yml
  apps/baidunetdisk/versions/latest/README.md
  apps/baidunetdisk/versions/latest/config.json
  apps/baidunetdisk/versions/latest/data/config/.gitkeep
  apps/baidunetdisk/versions/latest/data/downloads/.gitkeep
  apps/baidunetdisk/versions/latest/docker-compose.yml
  apps/flarum/versions/latest/README.md
  apps/flarum/versions/latest/config.json
  apps/flarum/versions/latest/docker-compose.yml
  apps/list.json
  apps/mysql/versions/5.5.62/README.md
  apps/mysql/versions/5.5.62/conf/my.cnf
  apps/mysql/versions/5.5.62/config.json
  apps/mysql/versions/5.5.62/docker-compose.yml
  apps/mysql/versions/5.6.51/README.md
  apps/mysql/versions/5.6.51/conf/my.cnf
  apps/mysql/versions/5.6.51/config.json
  apps/mysql/versions/5.6.51/docker-compose.yml
  apps/watchtower/versions/1.5.3/README.md
  apps/watchtower/versions/1.5.3/config.json
  apps/watchtower/versions/1.5.3/docker-compose.yml
Labels: do-not-merge/release-note-label-needed

#66 feat: openresty 隐藏版本号
  apps/openresty/versions/1.21.4.1/conf/nginx.conf
Labels: do-not-merge/release-note-label-needed

#67 Bump halo version to 2.5.2
  apps/halo/versions/2.5.2/README.md
  apps/halo/versions/2.5.2/config.json
  apps/halo/versions/2.5.2/docker-compose.yml
  apps/list.json
Labels: do-not-merge/release-note-label-needed

#70 fix: 修正qBitorrent端口映射问题及jellyfin镜像错误
  apps/jellyfin/versions/unstable/docker-compose.yml
  apps/list.json
  apps/qBittorrent/versions/4.3.5/data/.config/qBittorrent/qBittorrent.conf
  apps/qBittorrent/versions/4.3.5/docker-compose.yml
  apps/qBittorrent/versions/4.5.2/data/.config/qBittorrent/qBittorrent.conf
  apps/qBittorrent/versions/4.5.2/docker-compose.yml
  apps/qBittorrent/versions/latest/README.md
  apps/qBittorrent/versions/latest/config.json
  apps/qBittorrent/versions/latest/data/.cache/.gitkeep
  apps/qBittorrent/versions/latest/data/.config/qBittorrent/qBittorrent.conf
  apps/qBittorrent/versions/latest/data/.local/.gitkeep
  apps/qBittorrent/versions/latest/data/downloads/.gitkeep
  apps/qBittorrent/versions/latest/docker-compose.yml
Labels: do-not-merge/release-note-label-needed

#71 feat: 删除无用文件
  apps/list.json
  apps/vocechat/metadata/logo.png
  apps/vocechat/versions/0.3.0/README.md
  apps/vocechat/versions/0.3.0/config.json
  apps/vocechat/versions/0.3.0/docker-compose.yml
Labels: do-not-merge/release-note-label-needed

#72 feat: MySQL 容器时间与宿主机同步
  apps/mysql/versions/5.7.39/docker-compose.yml
  apps/mysql/versions/8.0.30/docker-compose.yml
Labels: do-not-merge/release-note-label-needed

#80 feat: 修改 waf 告警页面样式
  apps/openresty/versions/1.21.4.1/www/common/waf/access.lua
  apps/openresty/versions/1.21.4.1/www/common/waf/rules/html
  apps/openresty/versions/1.21.4.1/www/common/waf/rules/warn.html
Labels: do-not-merge/release-note-label-needed

#81 feat: 删除 jellyfin unstable 版本
  apps/jellyfin/versions/unstable/README.md
  apps/jellyfin/versions/unstable/config.json
  apps/jellyfin/versions/unstable/data/cache/.gitkeep
  apps/jellyfin/versions/unstable/data/config/.gitkeep
  apps/jellyfin/versions/unstable/data/media/.gitkeep
  apps/jellyfin/versions/unstable/docker-compose.yml
  apps/list.json
Labels: do-not-merge/release-note-label-needed

#82 fix: 修复 Gitea 对外暴露端口 key
  apps/gitea/versions/1.19.1/docker-compose.yml
Labels: do-not-merge/release-note-label-needed

#85 feat: minio 版本更新
  apps/list.json
  apps/minio/versions/RELEASE.2023-05-04T21-44-30Z/README.md
  apps/minio/versions/RELEASE.2023-05-04T21-44-30Z/config.json
  apps/minio/versions/RELEASE.2023-05-04T21-44-30Z/docker-compose.yml
Labels: do-not-merge/release-note-label-needed

#86 feat: 修改应用文字描述
  apps/list.json
Labels: do-not-merge/release-note-label-needed

#88 Add ehang-io/nps
  apps/list.json
  apps/nps/metadata/logo.png
  apps/nps/versions/0.26.10/README.md
  apps/nps/versions/0.26.10/conf/clients.json
  apps/nps/versions/0.26.10/conf/hosts.json
  apps/nps/versions/0.26.10/conf/multi_account.conf
  apps/nps/versions/0.26.10/conf/nps.conf
  apps/nps/versions/0.26.10/conf/server.key
  apps/nps/versions/0.26.10/conf/server.pem
  apps/nps/versions/0.26.10/conf/tasks.json
  apps/nps/versions/0.26.10/config.json
  apps/nps/versions/0.26.10/docker-compose.yml
Labels: do-not-merge/release-note-label-needed

#89 feat: add tailchat
  apps/list.json
  apps/tailchat/metadata/logo.png
  apps/tailchat/versions/1.7.3/README.md
  apps/tailchat/versions/1.7.3/config.json
  apps/tailchat/versions/1.7.3/docker-compose.yml
Labels: release-note

#90 feat:优化flarum外部访问;更新alist3.17.0;规范化;
  apps/alist/versions/3.17.0/README.md
  apps/alist/versions/3.17.0/config.json
  apps/alist/versions/3.17.0/data/data/.gitkeep
  apps/alist/versions/3.17.0/data/mnt/.gitkeep
  apps/alist/versions/3.17.0/docker-compose.yml
  apps/flarum/versions/1.7.1/config.json
  apps/flarum/versions/1.7.1/docker-compose.yml
  apps/jellyfin/versions/10.8.9/docker-compose.yml
  apps/list.json
  apps/qBittorrent/versions/4.3.5/docker-compose.yml
  apps/qBittorrent/versions/4.5.2/docker-compose.yml
Labels: do-not-merge/release-note-label-needed, lgtm

#92 feat: 删除 qBittorrent
  apps/qBittorrent/4.3.5/data.yml
  apps/qBittorrent/4.3.5/data/.cache/.gitkeep
  apps/qBittorrent/4.3.5/data/.config/qBittorrent/qBittorrent.conf
  apps/qBittorrent/4.3.5/data/.local/.gitkeep
  apps/qBittorrent/4.3.5/data/downloads/.gitkeep
  apps/qBittorrent/4.3.5/docker-compose.yml
  apps/qBittorrent/4.5.2/data.yml
  apps/qBittorrent/4.5.2/data/.cache/.gitkeep
  apps/qBittorrent/4.5.2/data/.config/qBittorrent/qBittorrent.conf
  apps/qBittorrent/4.5.2/data/.local/.gitkeep
  apps/qBittorrent/4.5.2/data/downloads/.gitkeep
  apps/qBittorrent/4.5.2/docker-compose.yml
  apps/qBittorrent/README.md
  apps/qBittorrent/data.yml
  apps/qBittorrent/logo.png
Labels: do-not-merge/release-note-label-needed

#93 feat: 应用商店支持 typecho
  apps/typecho/README.md
  apps/typecho/data.yml
  apps/typecho/logo.png
  apps/typecho/nightly-php7.4-apache/data.yml
  apps/typecho/nightly-php7.4-apache/docker-compose.yml
Labels: do-not-merge/release-note-label-needed

#94 feat: 应用商店增加禅道
  apps/dataease/1.18.6/data.yml
  apps/typecho/data.yml
  apps/typecho/logo.png
  apps/typecho/nightly-php7.4-apache/docker-compose.yml
  apps/zentao/18.2/data.yml
  apps/zentao/18.2/docker-compose.yml
  apps/zentao/README.md
  apps/zentao/data.yml
  apps/zentao/logo.png
Labels: do-not-merge/release-note-label-needed

#95 feat: halo 超级管理员用户名,限制修改
  apps/halo/2.5.2/data.yml
  apps/nexus/3.47.1/data/.gitkeep
Labels: do-not-merge/release-note-label-needed

#96 feat: 升级 openresty waf 配置
  apps/openresty/1.21.4.1/www/common/waf/access.lua
Labels: do-not-merge/release-note-label-needed
